shikkhashala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('notices/', views.notices, name='notices'),
    path('notices_detail/<int:id>/', views.notices_detail, name='notices_detail'),
    path('submit_number/', views.submit_number, name='submit_number'),
    path('gallery/', views.gallerys, name='gallery'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('login/', views.login, name='login'),
    path('logout/', views.admin_logout, name='logout'),
    path('profile_teacher/', views.profile_teacher, name='profile_teacher'),
    path('upload_topic/', views.upload_topic, name='upload_topic'),
    path('attandance_for/', views.attandance_for, name='attandance_for'),
    path('add_student_attandance/<courses>/', views.add_student_attandance, name='add_student_attandance'),
    path('profile_student/', views.profile_student, name='profile_student'),
    path('check_topic/', views.check_topic, name='check_topic'),
    path('topic_details/<int:id>/', views.topic_details, name='topic_details'),
    path('contact_success/', views.contact_success, name='contact_success'),
    path('enroll/<int:id>/', views.enroll, name='enroll'),
    path('download_routine/<int:id>/', views.download_routine, name='download_routine'),
    path('download_result/<courses>/', views.download_result, name='download_result'),
    path('download_reciept/', views.download_reciept, name='download_reciept'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class courses(models.Model):
    image = models.ImageField(upload_to='courses/')
    title = models.CharField(max_length=100)
    marketing_line = models.CharField(max_length=1000)
    description_for_card = RichTextUploadingField(blank=True, null=True)
    description = RichTextUploadingField(blank=True, null=True)

    def __str__(self):
        return self.title
    

class teachers(models.Model):
    image = models.ImageField(upload_to='students/', blank=True, null=True)
    user = models.ForeignKey('profile', on_delete=models.CASCADE, related_name='teachers') 
    description = RichTextUploadingField(blank=True, null=True)
    salary = models.IntegerField()


    def save(self, *args, **kwargs):
        if not self.image and self.user.image:
            self.image = self.user.image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.name.username
    
class teachers_attandance(models.Model):
    name = models.ManyToManyField("teachers", verbose_name=("Teachers"))
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class class_topic(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    courses = models.ManyToManyField("courses", verbose_name=("Courses"))
    description = RichTextUploadingField(blank=True, null=True)

    def __str__(self):
        return self.title


class routine(models.Model):
    title = models.CharField(max_length=100)
    courses = models.ManyToManyField("courses", verbose_name=("Courses"))
    routine_pdf = models.FileField(upload_to='routine/', default='routine/nonepdf.pdf')

    def __str__(self):
        return self.title
    
class results(models.Model):
    name = models.CharField(max_length=100)
    courses = models.ManyToManyField("courses", verbose_name=("Courses"))
    result = models.FileField(upload_to='results/', default='results/default.pdf')
    

    def __str__(self):
        return self.name
    
class students(models.Model):
    image = models.ImageField(upload_to='students/', blank=True, null=True)
    user = models.ForeignKey('profile', on_delete=models.CASCADE, related_name='students')   
    address = models.CharField(max_length=100)
    courses = models.ManyToManyField("courses", verbose_name=("Courses"))
    description = RichTextUploadingField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.image and self.user.image:
            self.image = self.user.image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.name.username

class students_attandance(models.Model):
    name = models.ManyToManyField("students", verbose_name=("Students"))
    date = models.DateField()

    def __str__(self):
        return str(self.date)


    
class contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

class gallery(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='gallery/')
    
    def __str__(self):
        return self.name


class carousel(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='carousel/')
    color = models.CharField(max_length=10)
    
    
    def __str__(self):
        return self.title
    
class student_payment(models.Model):
    name = models.ManyToManyField("students", verbose_name=("Students"))
    pay_for = models.CharField(max_length=100)
    paid_amount = models.IntegerField()
    paid_date = models.DateField()
    

    def __str__(self):
        return str(self.name.first())


class profile(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile/default.png', upload_to='profile/')
    
    def __str__(self):
        return f'{self.name.username}'
    def save(self, *args, **kwargs):
        super(profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image


class give_number(models.Model):
    number = models.IntegerField()
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.number)

class enroll(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.IntegerField()
    address = models.CharField(max_length=100)
    gurdian_name = models.CharField(max_length=100)
    gurdian_phone = models.IntegerField()
    gurdian_relation = models.CharField(max_length=100)
    courses = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class notices(models.Model):
    title = models.CharField(max_length=100)
    description = RichTextUploadingField(blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

templates/attandance_for.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section style="margin-top: 100px; margin-bottom: 200px;">
    <div>
        <h1 class="h1_enroll">Select class for attandance</h1>
    </div>
    <div class="container-fluid">
        <div class="text-center">
            {% for item in students_class %}
            <div style="margin-top: 5px; background-color: rgb(197, 197, 197);" class="row">
                <div class="col-6" style=" font-weight: bolder; font-size: 25px;">{{ item.title }}</div>
                <div class="col-6"><a href="{% url 'add_student_attandance' item.id %}" class="btn btn-primary">Select</a></div>
            </div>
            {% endfor %}
        </div>
    </div>

</section>








{% endblock %}

templates/check_topic.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1 style="margin-top: 100px; text-align: center; color: navy; font-weight: bolder;">Class topics</h1>
<div class="container" style="margin-bottom: 20px;">
    <div class="row">
        {% for item in topics %}
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <h2 class="card-title text-center">{{ item.title }}</h2>
                <h4 class="card-subtitle mb-2 text-body-secondary" style="text-align: right;">{{ item.date }}</h4>
                <p class="card-text">{{ item.description | slice:"0:30" | safe }}</p>
                <center><a href="{% url 'topic_details' item.id %}" class="btn btn-primary" style="width: 30%;">Details</a></center>
            </div>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

templates/contact_success.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<center>
    <div class="img-fluid">
        <img src="{% static 'img/name.png' %}" alt="" class="img-fluid" style=" margin-top: 80px;">
    </div>

</center>
<center>
    <div class="text-center" style="margin-top: 50px; color: navy;"><h2>ফর্ম জমা সম্পুর্ন হয়েছে</h2></div>
    <div class="text-center" style="margin-top: 50px; color: navy; margin-bottom: 100px;"><h2>খুব শিগ্রই আমাদের একজন এজেন্ট আপনার সাথে যোগাযোগ করবেন</h2></div>
</center>


{% endblock content %}

templates/enroll_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<center>
    <div class="img-fluid">
        <img src="{% static 'img/name.png' %}" alt="" class="img-fluid" style=" margin-top: 80px; width: 80%;">
    </div>

</center>
<center>
    <div class="text-center" style="margin-top: 50px; color: navy;"><h2>Enroll successful</h2></div>
    <div class="text-center" style="margin-top: 50px; color: rgb(95, 95, 250);"><h2>Our agent will contact you very soon</h2></div>
    <div><a href="{% url 'index' %}" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; width: 200px;">Go to home</a></div>
</center>





{% endblock %}

templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="head d-flex justify-content-center">
        <h1 class="head1" style="color: navy; font-weight: bolder; margin-top: 100px;">আমাদের গ্যালারি</h1>
        <hr style="color: navy; width: 50%; ">
        <h1 class="head2" style="color: navy; font-weight: bolder; margin-top: 100px;">Our Gallery</h1>
    </div>
    <center>
        <hr style="color: navy; width: 50%; ">
    </center>
    <div class="container-fluid">
        <div class="skill-cards-wrapper">
            <div class="row carditems">
                {% for item in gallery %}
                <div class="card"
                    style="width: 18rem; float: left; margin: 20px; padding: 0; background-image: url(../media/static/img/recourse/card-back.jpg); border-radius: 20px;">
                    <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                    <div class="card-body">
                        <center>
                            <h5 class="card-title" style="color: navy; font-size: 20px;">{{ item.name }}</h5>
                        </center>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>






{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container" style="margin-top: 100px; margin-bottom: 100px;">
    <div class="row">
      <div class="col-4 offset-4" style="background-color:whitesmoke; width: 35%;">
        <h1 class="text-center">Login</h1>
        <hr />
        <div class="col-12">
          <img src="{% static 'img/user-login.png' %}" style="width: 35%; margin-left: 33%;" alt="">
        </div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if messages %}
         {% for message in messages %}
          <p class="alert alert-warning">{{ message }}</p>
          {% endfor %}
          {% endif %}
          
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="name" name="name" placeholder="name@example.com">
            <label for="name">Username</label>
          </div>
          <div class="form-floating">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            <label for="password">Password</label>
          </div><br>
          <button type="submit" class="btn btn-primary" style="width: 100%">
            Log In
          </button>
          
          {% if error %}
          <p class="alert alert-danger">{{ error }}</p>{% endif %}

        </form>
        
        


      </div>
    </div>
  </div>







{% endblock content %}

templates/notices_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div style="font-weight: bolder ; color: navy;"><h1>{{ notice.title }}</h1></div>
    </div>
    <div class="row">
        <div><h3 style="color: rgb(78, 78, 78); font-weight: bolder">{{ notice.date }}</h3></div>
    </div>
    <div class="row">
        <div style="margin-top: 30px;"><h6>{{ notice.description | safe }}</h6></div>
    </div>
</div>
{% endblock %}

templates/profile_student.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="content-section" style="margin-top: 100px;">
  <center>
    <div class="media">
      <img class="rounded-circle account-img" src="{{ student.image.url }}" />
      <div class="media-body">
        <table>
          <tr>
            <td>
              <h2 class="account-heading" style="color: navy;">Name:</h2>
            </td>
            <td></td>
            <td>
              <h2 class="account-heading">{{ student.user }}</h2>
            </td>
          </tr>
          <tr>
            <td>
              <h4 style="color: navy;">Address:</h4>
            </td>
            <td></td>
            <td>
              <h4>{{ student.address }}</h4>
            </td>
          </tr>
          <tr>
            <td>
              <h4 style="color: navy;">Class:</h4>
            </td>
            <td></td>
            <td>
              <h4>{{ student.courses }}</h4>
            </td>
          </tr>
          <tr style="border: 1px solid navy;">
            <td>
              <h4 style="color: navy;">About:</h4>
            </td>
            <td></td>
            <td>
              <h6>{{ student.description|safe }}</h6>
            </td>
        </table>
      </div>
    </div>
  </center>
  <div>
    <center>
      <a href="{% url 'check_topic' %}" class="btn btn-primary"
        style="width: 40%; padding: 8px; margin-top: 5px;">Check class topics</a>
    </center>
    <center>
      <a href="{% url 'download_reciept' %}" class="btn btn-primary"
        style="width: 40%; padding: 8px; margin-top: 5px;">Download reciept</a>
    </center>
    <center>
      <a href="{% url 'download_result' student.courses %}" class="btn btn-primary"
        style="width: 40%; padding: 8px; margin-top: 5px;">Download result</a>
    </center>
    <center><a href="{% url 'logout' %}" class="btn btn-danger"
        style="width: 40%; padding: 8px; margin-top: 5px;">Logout</a>
    </center>
  </div>
  <br>
  <hr>
  <br>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center fs-1" style="color: navy;"><u>Attendence</u></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col"><center>Total Attendence: {{ attandance_count }}</center></th>
          </tr>
        </thead>
      </table>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col"><center>Date</center></th>
          </tr>
        </thead>
        <tbody>
          {% for attendence in attandance_new_ten %}
          <tr>
            <td><center>{{ attendence.date }}</center></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>



{% endblock %}

templates/reciept.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Shikkhashala</title>
</head>
<body style="background-color: wheat;">
    <center><img src="../static/img/name.png" alt="" style="width: 80%;"></center>
    <center><h1 style="font-weight: bolder; color: navy; margin-top: 20px;">Payment Reciept</h1></center>

    <table style="background-color: rgb(219, 219, 219); font-size: 15px;">
        <thead>
            <tr>
                <th>Serial No</th>
                <th>Description</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
            
        </thead>
        <tbody>
            {% for reciept in payment %}
            <tr style="text-align: center; margin: 10px;">
                <td>{{ forloop.counter }}</td>
                <td>{{ reciept.pay_for }}</td>
                <td>{{ reciept.paid_date }}</td>
                <td>{{ reciept.paid_amount }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr></tr>
            <tr>
                <td></td>
                <td></td>
                <td style="text-align: right; font-weight: bolder;">Total:</td>
                <td style="text-align: center; font-weight: bolder;">{{ total }}</td>
            </tr>
        </tfoot>
    </table>

</body>
</html>

templates/student_attandance.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.jpg' %}">
    <title>Shikkhashala</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        body {
            background-image: url("{% static 'img/background.jpg' %}");
        }
        .h1_enroll {
            color: navy;
            text-align: center;
        }

        form {
            max-width: 100%;
            margin: 0 auto;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        p {
            color: black;
            font-weight: bold;
        }

        #id_courses {
            width: 300px;
            font-size: 15px;
        }

        select {
            width: 300px;
            font-size: 15px;
        }
    </style>
</head>

<body>
    <!-- Navigation bar section -->
    <section>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong fixed-top" style="color: black;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'index' %}"
                        style="color: white; font-family: Times New Roman;font-size: 30px;"
                        class="d-inline-block align-text-top"><span><img src="{% static 'img/logo.jpg' %}" alt="Logo"
                                width="50" height="50"
                                style="border-radius: 100%; margin-right: 10px;"></span>Shikkhashala</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse textcol" id="navbarNav" style="margin-left: 50%;">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'index' %}"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/index#courses"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/index#teachers_panel"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Teachers
                                    panel</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'gallery' %}"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Gallery</a>
                            </li>
                        </ul>
                        <a class="btn btn-primary text-center" href="{% url 'contact_us' %}" role="button"
                            style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Contact
                            us</a>
                    </div>
                </div>
            </nav>

        </header>
    </section>

    <section style="margin-top: 100px; margin-bottom: 100px;">
        <h1 class="h1_enroll">Add Student Attandance</h1>
        <form method="post" style="width: 100%;">
            {% csrf_token %}
            <select class="form-select" multiple aria-label="Multiple select example" name="name" id="name">
                {% for item in students %}
                <option value="{{ item.pk }}" style="font-size: 15px;">{{ item.user }}</option>
                {% endfor %}
            </select><br><br><br>
            <label for="id_date"><b>Date: </b></label>
            <input type="date" name="date" required="" id="id_date">
            <input type="submit" value="Submit">
        </form>
    </section>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        // Get the button
        let mybutton = document.getElementById("myBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }

    </script>
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
</body>

</html>

templates/topic_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div style="font-weight: bolder ; color: navy;"><h1>{{ topic.title }}</h1></div>
    </div>
    <div class="row">
        <div><h3 style="color: rgb(78, 78, 78); font-weight: bolder">{{ topic.date }}</h3></div>
    </div>
    <div class="row">
        <div style="margin-top: 30px;"><h6>{{ topic.description | safe }}</h6></div>
    </div>
</div>

<div>
    <center><a href="{% url 'profile_student' %}" class="btn btn-primary" style="margin-top: 20px; margin-bottom: 20px; width: 200px;">Back to profile</a></center>
</div>



{% endblock %}

templates/upload_topic.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.jpg' %}">
    <title>Shikkhashala</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        .h1_enroll {
            color: navy;
            text-align: center;
        }
        form {
            max-width: 100%;
            margin: 0 auto;
        }
        input[type="text"], textarea {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }
        input[type="submit"]:hover {
            background-color: #45a049;
        }
        p{
            color: black;
            font-weight: bold;
        }
        #id_courses {
            width: 300px;
            font-size: 15px;
        }
    </style>
</head>

<body style="background-image: url(../media/static/img/recourse/background.jpg);">
    <!-- Navigation bar section -->
    <section>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong fixed-top" style="color: black;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'index' %}"
                        style="color: white; font-family: Times New Roman;font-size: 30px;"
                        class="d-inline-block align-text-top"><span><img src="{% static 'img/logo.jpg' %}" alt="Logo"
                                width="50" height="50"
                                style="border-radius: 100%; margin-right: 10px;"></span>Shikkhashala</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse textcol" id="navbarNav" style="margin-left: 50%;">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'index' %}"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/index#courses"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/index#teachers_panel"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Teachers
                                    panel</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'gallery' %}"
                                    style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Gallery</a>
                            </li>
                        </ul>
                        <a class="btn btn-primary text-center" href="{% url 'contact_us' %}" role="button"
                            style="font-family: Arial, Helvetica, sans-serif;font-size: 18px; color: white;">Contact
                            us</a>
                    </div>
                </div>
            </nav>

        </header>
    </section>

   <section style="margin-top: 100px; margin-bottom: 100px;">
    <h1 class="h1_enroll">Upload Topic</h1>
    <form method="post" style="width: 100%;">
        {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <input type="submit" value="Submit">
    </form>
   </section>


   



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        // Get the button
        let mybutton = document.getElementById("myBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }

    </script>
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
</body>

</html>